### ISSUE TITLE
HELP：请教下 Chrome-extension 部署方法

### ISSUE THREAD

**Issue by Spider-DT** [notelix/notelix#13]
### 步骤1
在云主机上执行 ./ build extension.sh，完成后提示：
![image](https://user-images.githubusercontent.com/60735795/159291471-474d2f7a-ef8a-46a1-975d-15f19f4342ba.png)
### 步骤2
将浏览器扩展拖到 Chrome 中安装，可以使用 DEV 环境的 notelix
![image](https://user-images.githubusercontent.com/60735795/159292780-4b803fff-9239-41c0-8086-abfbac373a4e.png)

---
## 请问：
* 这里的 **Change Server** 在步骤1 完成后，是否可以替换成自己的云主机IP？只需要IP就可以，还是说需要对应端口？

**Comment by KevinWang15** [comment]
Hi @Spider-DT , 可以自己部署Notelix服务器（后端）的，目前这个项目还比较新，数据模型等还可能发生变化，如果打算长期使用，自己部署自己管理自己的数据也是推荐的方式。

这里有后端部署的说明： https://github.com/notelix/notelix#building-and-running-backend  用docker-compose来部署，基本上是一键部署。默认后端会监听在18555端口上。也可以再跑个Nginx反向代理，比如

```
server {
    listen 443 ssl;
    gzip on;
    gzip_types    text/plain application/javascript application/x-javascript text/javascript text/xml text/css;

    ssl_certificate        /etc/ssl/notelix.com.crt;
    ssl_certificate_key    /etc/ssl/notelix.com.key;

    server_name public-dev.notelix.com;

    location /embedded/ {
        root /var/www/notelix-embedded/;
    }

    location / {
        proxy_pass http://127.0.0.1:18555/;
    }
}
```

这样就可以在其它端口访问，加ssl证书等

**Comment by KevinWang15** [comment]
后端部署完成后，先用浏览器访问一下试试，能够访问通，点Change Server改成自己的云主机IP就行
<img width="417" alt="image" src="https://user-images.githubusercontent.com/10173472/159395063-2e4281ee-41e9-4a88-b965-7a3e56108a37.png">

**Comment by Spider-DT** [comment]
@KevinWang15  多谢，已成功部署
觉得 readme 可以写的详细些，并且也可以有个中文版，这一块我来做点能做的吧

**Comment by Spider-DT** [comment]
多问一个问题：部署后端(https://github.com/notelix/notelix#building-and-running-backend) 和 build 浏览器插件 这两部的关系是？
是不是只有部署后端成功后，build的浏览器插件才能和后端形成联动，存储持久化标注数据？

**Comment by KevinWang15** [comment]
@Spider-DT 这两步之间没有必然关系， build浏览器插件是可选的，如果不想build，release页面里有已经build好的zip，直接下载安装就行； 部署自己的后端也是可选的，如果不部署自己的后端，可以用公共dev服务器（虽然这个服务器不保证数据可靠），或者其他人部署的服务器

插件和哪个后端形成联动跟build插件的机器没有关系，是插件安装完以后点Change Server后填入的后端地址决定的

**Comment by KevinWang15** [comment]
目前这个项目还比较新，roadmap里很多功能还没实现，等再完善一些之后，README、中文README可以再搞搞

**Comment by Spider-DT** [comment]
THX
